### ISSUE TITLE
Allow configuration of the base URL for PlantUML Server

### ISSUE THREAD

**Issue by kellerj** [adrianvlupu/C4-Builder#15]
I would like to be able to have the speed of rapid page updates without the dependency on an outside server.  It would be nice if that (like the VS Code extension), you could configure the `plantUmlServerUrl` to use a per-project configured value instead of the default plantuml.com host.

**Comment by dev-lusaja** [comment]
I for security reason need to use a local server for create diagrams U_U

**Comment by jikuja** [comment]
**Generate diagram images locally** option can be used to invoke diagram image generation locally. 

Making base URL configurable should be fairly easy and while doing POST support could be added.

**Comment by adrianvlupu** [comment]
Fixed by https://github.com/adrianvlupu/C4-Builder/pull/29
