### ISSUE TITLE
Outdated PlantUML version or broken C4-PlantUML?

### ISSUE THREAD

**Issue by Berkmann18** [adrianvlupu/C4-Builder#36]
I've noticed that on some C4-Build-based projects, the generated diagrams end up being along the lines of 
![image](https://user-images.githubusercontent.com/8260834/116622971-740c6280-a93d-11eb-9b03-6ec95bff9ef1.png) (cf. https://ac-architecture.netlify.app/#/) and even trying to change the config to have the `generateLocalImages`/`embedDiagram``and such set differently as well as using `https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml` over `https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml` lead to failed images (which doesn't happen locally when using the PlantUML VSC extension).

**Comment by vellala2000** [comment]
I came across the same issue. please let us know how to address this

**Comment by adrianvlupu** [comment]
The issue is with a broken url to tupadr3/plantuml-icon-font-sprites.
Replace /dev2 with /devicons
