### ISSUE TITLE
Relative paths for navigation links.

### ISSUE THREAD

**Issue by luisrayas3** [adrianvlupu/C4-Builder#5]
It seems that when the output is multiple markdown files the navigation link targets are preceded by '/' which when viewed on GitHub links relative to the project root and causes problems when the c4builder project is not located at the repository's root. I think it is reasonable to expect the documentation to be in a directory not at root.

**Comment by tomschreck** [comment]
I'm experiencing the same issue.  How do you make multiple markdown files use relative paths?

![image](https://user-images.githubusercontent.com/2521463/140615212-54d0e00f-736a-4c24-ad56-d4e90ec9de30.png)

**Comment by adrianvlupu** [comment]
Thanks for the screenshot. I finally understood what the issue was, having multiple markdowns in github in a mono-repo like folder structure.

I played around with the demo project and it should be fixed now.
