### ISSUE TITLE
_sidebar.md gets 404 for any file not in the root of the distFolder

### ISSUE THREAD

**Issue by GregEisenberg** [adrianvlupu/C4-Builder#52]
Root issue: _sidebar.md gets 404 for any file not in the root of the distFolder

Context: 
We are following the source layout example provided in the readme and using the sidebar=true option.  After building, the `distFolder` has a file called `_sidebar.md`. The top level `index.html` and `Home.md` file renders perfectly and work correctly.  However for every page in any subfolders of the `distFolder`,  they fail to find _sidebar.md because those subfolder do not have that file.  Looking at the web debugger is that it seems to make requests for `_sidebar.md` once per level in the tree.. but no request from a page below the root of `distFolder` makes the request for the topmost. 

Its possible that what I am hitting is really https://github.com/docsifyjs/docsify/issues/1713 but wanted to call it out here too.

**Comment by GregEisenberg** [comment]
Per comments provided to me in [here](https://github.com/docsifyjs/docsify/issues/1713#issuecomment-1042470827) adding 
```
      "alias": {
        '/.*/_sidebar.md': '/_sidebar.md'
      },
```
in `index.html`'s `window.$docsify` object did fix the issue.  Looking to see if i can find where that index.html is generated and will see if I can provide a PR, otherwise it seems the solution is clear just need to figure out how to implement it.

**Comment by MickeJohannesson** [comment]
It's located in the docsify.template.js file.
The injection of the options are made in build.js (look for docsify homepage)
I have added this one fix also into my PR #56

**Comment by adrianvlupu** [comment]
It should be fixed now (hopefully)

**Comment by GregEisenberg** [comment]
Awesome!  Thanks for the reply and the updated version!  Will look to test it out soon.
