### ISSUE TITLE
Update plantuml jar to the latest version

### ISSUE THREAD

**Issue by vellala2000** [adrianvlupu/C4-Builder#54]
PUML json file to image conversion is failing in some cases with error message "your data doesn't sound like json data"
probably due to old plantuml jar version. Where as its working okay using vscode plugin and on plantuml site.

**Comment by vellala2000** [comment]
looks like #title is the culprit for failing in current available version of plantuml. however it would be nice to have latest version

**Comment by MickeJohannesson** [comment]
In my PR #56 I added plantuml-1.2022.1.jar 
Are you able to verify if that one solves your problem?

**Comment by vellala2000** [comment]
yeah its working with latest version

**Comment by adrianvlupu** [comment]
Included 1.2022.3 in the latest update

**Comment by vellala2000** [comment]
Awesome. Thank you @adrianvlupu !!
