### ISSUE TITLE
snyk vulnerablity on  minimist@0.0.8 (only)

### ISSUE THREAD

**Issue by mailtoraja18** [adrianvlupu/C4-Builder#6]
Dependency: NPM - minimist@0.0.8
          Type:               VULNERABILITY
          Name:               SNYK-JS-MINIMIST-559764
          CVSS Score v3:      8.4
          Severity:           high
          Description Link:   https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

**Comment by mailtoraja18** [comment]
https://github.com/substack/minimist

Please use version 1.2.3 or later: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

**Comment by adrianvlupu** [comment]
Hi, thanks for the issue.

`npm audit` no longer returns any vulnerabilities
