### ISSUE TITLE
Diagrams at arbitrary positions not working for more than one file

### ISSUE THREAD

**Issue by vellala2000** [adrianvlupu/C4-Builder#62]
When there is more than one `![name](name.puml)` in a .md file, build replacing all the file with the first one.

```
// test.md file

![name1](name1.puml) 
![name2](name2.puml) 
```

after running build all .puml references are replace with first .svg file, 

```
//afterbuild.md file

![diagram](name1.svg)
![diagram](name1.svg)
```

expected

```
//afterbuild.md file

![diagram](name1.svg)
![diagram](name2.svg)
```

**Comment by adrianvlupu** [comment]
You are right, MickeJohannesson fixed it. It should be ok now.

**Comment by vellala2000** [comment]
Thank you !!. @MickeJohannesson @adrianvlupu
